export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";
export const REQUEST_ROBOCATS_PENDING = "REQUEST_ROBOCATS_PENDING";
export const REQUEST_ROBOCATS_SUCCESS = "REQUEST_ROBOCATS_SUCCESS";
export const REQUEST_ROBOCATS_FAILED = "REQUEST_ROBOCATS_FAILED";